### ISSUE TITLE
GSoC 2015 - Testing

### ISSUE THREAD

**Issue by kaushik94** [tardis-sn/tardis#295]
This can wait until #293 gets finished(or at least partly). First thing to do is to figure out whats going on with the setup files, and tweak them if necessary. Also relating to #272
- [x] Finish #293 
- [x] create a testing framework
- [x] Test basic getters and setters( #327 )
- [x] Test other simple distance functions in montecarlo( #330 )
- [ ] Test the following
  - [x] `move_packet`
  - [x] `rpacket_doppler_factor`
  - [x] `montecarlo_line_scatter`
  - [x] `montecarlo_thomson_scatter`
  - [x] `montecarlo_bound_free_scatter`
  - [x] `montecarlo_free_free_scatter`
  - [x] `move_packet_across_shell_boundary`
  - [x] `increment_j_blue_estimator`
  - [ ] `macro_atom`
  - [x] `montecarlo_one_packet_loop` (All the above tests should be first done, uses them as handlers)
  - [x] `montecarlo_one_packet` (Uses `montecarlo_one_packet_loop`)
  - [ ] `montecarlo_main_loop`
  - [x] `calculate_chi_bf`
  - [x] `bf_cross_section`
- [x] Fill the actual values of RPacket and Storage Model in #330.

**Comment by wkerzendorf** [comment]
This is the todo list for the testing of the C-part, right? Can you link this on trello? https://trello.com/b/z8rZdn9c/tardis-15-revamp

**Comment by kaushik94** [comment]
I think I'm not added to the org in trello, unable to add any cards.

**Comment by wkerzendorf** [comment]
@kaushik94 you should be added
